version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.5-management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  db:
    image: postgres:13.4-alpine
    env_file:
      .env
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 5
  web:
    build:
      context: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "mercadobitcoin.asgi:application"]
    env_file:
      .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  celery_worker:
    build:
      context: .
    command: ["celery", "-A", "mercadobitcoin", "worker", "-l", "INFO"]
    env_file:
      .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  celery_beat:
    build:
      context: .
    command: ["celery", "-A", "mercadobitcoin", "beat", "-l", "INFO"]
    env_file:
      .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
