# Generated by Django 3.2.6 on 2021-09-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mms',
            options={'verbose_name': 'MMS', 'verbose_name_plural': 'MMS'},
        ),
    ]
